### ISSUE TITLE
Error when running gm1356

### ISSUE THREAD

**Issue by VijayDoshi** [ciembor/gm1356-linux-driver#4]
Hi, I am getting this when I run the gm1356. Any hints as to what I am doing wrong?

pi@raspberrypi:~ $ gm1356 
Traceback (most recent call last):
	6: from /usr/local/bin/gm1356:23:in `<main>'
	5: from /usr/local/bin/gm1356:23:in `load'
	4: from /var/lib/gems/2.5.0/gems/gm1356-0.0.4/bin/gm1356:40:in `<top (required)>'
	3: from /var/lib/gems/2.5.0/gems/gm1356-0.0.4/bin/gm1356:40:in `new'
	2: from /var/lib/gems/2.5.0/gems/gm1356-0.0.4/lib/gm1356/device.rb:16:in `initialize'
	1: from /var/lib/gems/2.5.0/gems/gm1356-0.0.4/lib/gm1356/device.rb:48:in `read_current_state'
/var/lib/gems/2.5.0/gems/gm1356-0.0.4/lib/gm1356/device.rb:63:in `send_state_request': undefined method `write' for nil:NilClass (NoMethodError)

Thanks!

**Comment by VijayDoshi** [comment]
This can be resolved I had to look up the device name and add a 0x to the string.
