### ISSUE TITLE
Libusb busy

### ISSUE THREAD

**Issue by beerebear** [ciembor/gm1356-linux-driver#5]
After successfully recording for a time, I sometimes get the following:

```
pi@raspberrypi:~ $ sudo gm1356
21:00:50 	 SPL: 50.2dBA
21:00:51 	 SPL: 30.5dBA
21:00:52 	 SPL: 30.8dBA
21:00:53 	 SPL: 30.9dBA
21:00:54 	 SPL: 30.9dBA
21:00:55 	 SPL: 30.3dBA
#<Thread:0x0217baf8@/var/lib/gems/2.5.0/gems/gm1356-0.0.4/lib/gm1356/device.rb:26 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	8: from /var/lib/gems/2.5.0/gems/gm1356-0.0.4/lib/gm1356/device.rb:27:in `block (2 levels) in read'
	7: from /var/lib/gems/2.5.0/gems/gm1356-0.0.4/lib/gm1356/device.rb:48:in `read_current_state'
	6: from /var/lib/gems/2.5.0/gems/gm1356-0.0.4/lib/gm1356/device.rb:63:in `send_state_request'
	5: from /var/lib/gems/2.5.0/gems/hidapi-0.1.9/lib/hidapi/device.rb:280:in `write'
	4: from /var/lib/gems/2.5.0/gems/libusb-0.5.1/lib/libusb/dev_handle.rb:455:in `interrupt_transfer'
	3: from /var/lib/gems/2.5.0/gems/libusb-0.5.1/lib/libusb/dev_handle.rb:534:in `submit_transfer'
	2: from /var/lib/gems/2.5.0/gems/libusb-0.5.1/lib/libusb/transfer.rb:168:in `submit_and_wait'
	1: from /var/lib/gems/2.5.0/gems/libusb-0.5.1/lib/libusb/transfer.rb:141:in `submit!'
/var/lib/gems/2.5.0/gems/libusb-0.5.1/lib/libusb/constants.rb:62:in `raise_error': LIBUSB::ERROR_BUSY in libusb_submit_transfer (LIBUSB::ERROR_BUSY)
#<Thread:0xb5957710@/var/lib/gems/2.5.0/gems/gm1356-0.0.4/lib/gm1356/device.rb:26 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	5: from /var/lib/gems/2.5.0/gems/gm1356-0.0.4/lib/gm1356/device.rb:27:in `block (2 levels) in read'
	4: from /var/lib/gems/2.5.0/gems/gm1356-0.0.4/lib/gm1356/device.rb:48:in `read_current_state'
	3: from /var/lib/gems/2.5.0/gems/gm1356-0.0.4/lib/gm1356/device.rb:63:in `send_state_request'
	2: from /var/lib/gems/2.5.0/gems/hidapi-0.1.9/lib/hidapi/device.rb:280:in `write'
	1: from /var/lib/gems/2.5.0/gems/libusb-0.5.1/lib/libusb/dev_handle.rb:455:in `interrupt_transfer'
/var/lib/gems/2.5.0/gems/libusb-0.5.1/lib/libusb/dev_handle.rb:539:in `submit_transfer': error TRANSFER_TIMED_OUT (LIBUSB::ERROR_TIMEOUT)
Traceback (most recent call last):
	8: from /var/lib/gems/2.5.0/gems/gm1356-0.0.4/lib/gm1356/device.rb:27:in `block (2 levels) in read'
	7: from /var/lib/gems/2.5.0/gems/gm1356-0.0.4/lib/gm1356/device.rb:48:in `read_current_state'
	6: from /var/lib/gems/2.5.0/gems/gm1356-0.0.4/lib/gm1356/device.rb:63:in `send_state_request'
	5: from /var/lib/gems/2.5.0/gems/hidapi-0.1.9/lib/hidapi/device.rb:280:in `write'
	4: from /var/lib/gems/2.5.0/gems/libusb-0.5.1/lib/libusb/dev_handle.rb:455:in `interrupt_transfer'
	3: from /var/lib/gems/2.5.0/gems/libusb-0.5.1/lib/libusb/dev_handle.rb:534:in `submit_transfer'
	2: from /var/lib/gems/2.5.0/gems/libusb-0.5.1/lib/libusb/transfer.rb:168:in `submit_and_wait'
	1: from /var/lib/gems/2.5.0/gems/libusb-0.5.1/lib/libusb/transfer.rb:141:in `submit!'
/var/lib/gems/2.5.0/gems/libusb-0.5.1/lib/libusb/constants.rb:62:in `raise_error': LIBUSB::ERROR_BUSY in libusb_submit_transfer (LIBUSB::ERROR_BUSY)
```

Any hints?

**Comment by beerebear** [comment]
I found a workaround and maybe this will help someone else. I changed how often the dB level was recorded in device.rb from 1 seconds to 5 seconds. Wish I thought of this earlier!
